---
name: Aide CI Linux

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        compiler: [gcc, clang]
        crypto: [libmhash-dev, libgnutls28-dev, libgcrypt-dev]

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt install make pkg-config autoconf-archive bison flex libpcre2-dev zlib1g-dev check ${{ matrix.crypto }}
      - name: autoconf
        run: sh autogen.sh
      - name: configure
        run: |
          if [ "${{ matrix.crypto }}" = "libgnutls28-dev" ]; then
            ./configure --without-gcrypt
          else
            ./configure
          fi
        env:
          CC: ${{ matrix.compiler }}
          CFLAGS: -Werror -Wall -pedantic -g
      - name: make
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: |
          if [ "${{ matrix.crypto }}" = "libgnutls28-dev" ]; then
            export DISTCHECK_CONFIGURE_FLAGS="--without-gcrypt"
          fi
          make distcheck
