---
name: AIDE CI macOS

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        compiler: [gcc, clang]
        crypto: [gnutls, nettle, libgcrypt]

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: brew install autoconf autoconf-archive automake bison pkg-config ${{ matrix.crypto }} pcre check
      - name: update path
        run: echo /opt/homebrew/opt/bison/bin >> ${GITHUB_PATH}
      - name: autoconf
        run: ./autogen.sh
      - name: configure
        run: |
          if [ "${{ matrix.crypto }}" = "gnutls" ]; then
            ./configure --without-nettle --without-gcrypt
          else
            ./configure --without-gnutls
          fi
        env:
          CC: ${{ matrix.compiler }}
      - name: make
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: |
          if [ "${{ matrix.crypto }}" = "gnutls" ]; then
            export DISTCHECK_CONFIGURE_FLAGS="--without-nettle --without-gcrypt"
          else
            export DISTCHECK_CONFIGURE_FLAGS="--without-gnutls"
          fi
          make distcheck
